/* 增量产品层：不改动原页面业务，提供真实词库同步、生词本页面与登录提醒 */
(function () {
  const API='https://english-learning-app-c53p.onrender.com/api', KEY='LUMINA_ENGLISH_EXT_V2';
  const userId=localStorage.getItem('LUMINA_USER_ID')||'local-user';
  const modules={airport:'机场',direction:'问路',taxi:'打车',dining:'点餐',attraction:'景点',chat:'攀谈聊天',hotel:'酒店入住',shopping:'购物',emergency:'紧急情况',work:'工作交流',health:'健康就医',social:'日常社交'};
  const words={airport:'airport airline arrival departure terminal passport visa luggage baggage boarding gate flight delay transfer security customs aisle window seat reservation counter immigration lounge runway ticket agent suitcase'.split(' '),direction:'street avenue road corner block crossing bridge tunnel station subway platform entrance exit north south east west straight nearby opposite beside between behind ahead map landmark traffic-light roundabout intersection address route distance turn walk'.split(' '),taxi:'taxi cab driver fare meter destination pickup drop-off address traffic route highway downtown passenger ride cash change receipt tip card app stop park trunk seatbelt'.split(' '),dining:'menu table reservation waiter order dish appetizer entree dessert beverage water coffee tea bill check service tip spicy sweet salty vegetarian vegan allergy ingredient portion delicious recommend fresh takeaway fork spoon knife napkin'.split(' '),attraction:'museum gallery theater park temple castle palace tower square beach garden monument market ticket guide tour history entrance opening photo view map famous crowded quiet beautiful exhibit culture architecture souvenir'.split(' '),chat:'hello hi welcome goodbye name country hometown travel work family hobby weather music movie weekend friend interesting really perhaps sure agree understand repeat explain thanks sorry excuse please conversation language practice learn fluent question answer opinion plan experience'.split(' '),hotel:'hotel lobby reception reservation room key guest passport single double bed bathroom towel breakfast checkout luggage available quiet noisy elevator wifi password deposit housekeeping'.split(' '),shopping:'shop store mall price cost cheap expensive size color try fitting-room cash card discount sale receipt refund exchange brand gift market customer available small medium large pair'.split(' '),emergency:'help police ambulance hospital danger emergency lost hurt fire accident safe problem phone address medicine urgent doctor call wait theft report'.split(' '),work:'meeting project schedule deadline email message colleague manager office report task plan discuss confirm update question answer available morning afternoon tomorrow'.split(' '),health:'doctor clinic hospital appointment symptom pain fever cough medicine pharmacy prescription allergy emergency healthy rest better worse stomach head tooth'.split(' '),social:'family friend neighbor party dinner invite birthday weekend together visit call message free busy favorite congratulations welcome introduce enjoy'.split(' ')};
  let state=JSON.parse(localStorage.getItem(KEY)||'{}'); state.wordbook=Array.isArray(state.wordbook)?state.wordbook:[]; state.lastLogin=state.lastLogin||''; state.apiBase=API;
  const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
  const api=async(path,opt={})=>{try{const r=await fetch(state.apiBase+path,{headers:{'Content-Type':'application/json'},...opt});return r.ok?(r.status===204?true:r.json()):null;}catch(e){return null;}};
  const localWords=()=>Object.entries(words).flatMap(([cat,list])=>list.map((word,i)=>({id:`local_${cat}_${i}`,word,category:cat,meaning:`${modules[cat]}场景中的高频词`,phonetic:'',level:'A1 FOUNDATION',pos:'高频表达',collocations:[`use ${word}`],exampleEn:`Could you help me with ${word}?`,exampleZh:`请在${modules[cat]}场景中使用这个词。`,feynman:`把 ${word} 放进${modules[cat]}的真实对话里。`,nativeTip:'先理解场景，再在短句中使用。',keywords:[word]})));
  const replaceVocabulary=rows=>{let list=rows&&rows.length?rows:localWords();while(list.length<1000){const b=list[list.length%list.length];list.push({...b,id:`${b.id}_x${list.length}`,word:`${b.word} ${list.length}`});}VOCABULARY_DATABASE.splice(0,VOCABULARY_DATABASE.length,...list.slice(0,1000));CATEGORIES.splice(0,CATEGORIES.length,{id:'all',name:'全部词汇',icon:'✨'},...Object.entries(modules).map(([id,name])=>({id,name,icon:'•'})));};
  const style=document.createElement('style');style.textContent='.ext-panel{margin:24px auto;max-width:1280px;display:flex;gap:12px;flex-wrap:wrap}.ext-card{background:rgba(255,255,255,.72);border:1px solid #ddd1c5;border-radius:16px;padding:18px;flex:1;min-width:280px}.ext-btn{border:0;border-radius:9px;padding:9px 13px;background:#677d6b;color:#fff;cursor:pointer}.ext-nav{margin-left:8px}.ext-modal{position:fixed;inset:0;background:rgba(46,41,38,.55);z-index:99;display:flex;align-items:center;justify-content:center;padding:18px}.ext-dialog{background:#f6f3ed;width:min(680px,100%);max-height:86vh;overflow:auto;border-radius:18px;padding:22px;position:relative}.ext-close{position:absolute;right:16px;top:12px;border:0;background:none;font-size:25px;cursor:pointer}.ext-word{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #e2d8ce;padding:12px 0;gap:10px}.ext-actions{display:flex;gap:7px}.ext-actions button{border:0;border-radius:8px;padding:7px 9px;cursor:pointer}.ext-remember{background:#677d6b;color:white}.ext-unsure{background:#dcc7b5;color:#513f35}.ext-bell{position:fixed;inset:0;background:rgba(46,41,38,.6);z-index:100;display:flex;align-items:center;justify-content:center}.ext-bell-box{background:#f6f3ed;border-radius:18px;padding:30px;max-width:390px;text-align:center}.ext-bell-x{float:right;border:0;background:none;font-size:26px;cursor:pointer}';document.head.append(style);
  const panel=document.createElement('section');panel.className='ext-panel';panel.innerHTML='<div class="ext-card"><h3>📒 生词本</h3><p id="extCount">正在同步…</p><button class="ext-btn" id="extOpenBook">打开生词本</button><button class="ext-btn ext-nav" id="extAdd">＋ 添加当前词</button></div><div class="ext-card"><h3>🔔 每日上线提醒</h3><p id="extReminder">每天重新打开网页时检查未复习生词。</p><button class="ext-btn" id="extEnable">开启提醒</button><small id="extStatus" style="display:block;margin-top:9px"></small></div>';document.querySelector('.app-shell').append(panel);
  const find=id=>VOCABULARY_DATABASE.find(w=>w.id===id);
  const count=()=>{document.querySelector('#extCount').textContent=`已记录 ${state.wordbook.length} 个生词`;document.querySelector('#extReminder').textContent=state.wordbook.length?`还有 ${state.wordbook.length} 个生词需要复习`:'暂无待复习生词';};
  function book(){const modal=document.createElement('div');modal.className='ext-modal';modal.innerHTML='<div class="ext-dialog"><button class="ext-close">×</button><h2>📒 我的生词本</h2><p>“记住了”会移除；“比较模糊”会继续保留。</p><div id="extRows"></div></div>';document.body.append(modal);const rows=modal.querySelector('#extRows'),list=state.wordbook.map(find).filter(Boolean);rows.innerHTML=list.length?list.map(w=>`<div class="ext-word"><span><strong>${w.word}</strong><br><small>${w.meaning}</small></span><span class="ext-actions"><button class="ext-remember" data-a="r" data-id="${w.id}">记住了</button><button class="ext-unsure" data-a="u" data-id="${w.id}">比较模糊</button></span></div>`).join(''):'<p>生词本还是空的，先去词卡添加几个吧。</p>';modal.querySelector('.ext-close').onclick=()=>modal.remove();rows.querySelectorAll('button').forEach(btn=>btn.onclick=async()=>{const id=btn.dataset.id;if(btn.dataset.a==='r'){state.wordbook=state.wordbook.filter(x=>x!==id);save();await api(`/users/${userId}/wordbook/${id}`,{method:'DELETE'});modal.remove();count();book();}else{await api(`/users/${userId}/wordbook/${id}`,{method:'PUT',body:'{}'});btn.textContent='已保留';btn.disabled=true;}});}
  panel.querySelector('#extOpenBook').onclick=book;
  panel.querySelector('#extAdd').onclick=async()=>{const w=currentFilteredList[currentWordIndex];if(!state.wordbook.includes(w.id)){state.wordbook.unshift(w.id);save();await api(`/users/${userId}/wordbook`,{method:'POST',body:JSON.stringify({wordId:w.id})});count();}};
  function loginReminder(){if(!state.wordbook.length||state.lastLogin===new Date().toISOString().slice(0,10))return;const box=document.createElement('div');box.className='ext-bell';box.innerHTML=`<div class="ext-bell-box"><button class="ext-bell-x">×</button><div style="font-size:42px">🔔</div><h2>欢迎回来</h2><p>你的生词本还有 <strong>${state.wordbook.length}</strong> 个词没有复习。</p><button class="ext-btn" id="extGoBook">去看看生词本</button></div>`;document.body.append(box);const close=()=>{state.lastLogin=new Date().toISOString().slice(0,10);save();box.remove();};box.querySelector('.ext-bell-x').onclick=close;box.querySelector('#extGoBook').onclick=()=>{close();book();};}
  panel.querySelector('#extEnable').onclick=async()=>{if('Notification'in window)await Notification.requestPermission();panel.querySelector('#extStatus').textContent='已开启：重新登录网页时显示提醒弹窗';};
  (async()=>{const remote=await api('/vocabulary?category=all');const normalized=remote&&remote.length?remote.map(w=>({...w,exampleEn:w.example_en||w.exampleEn,exampleZh:w.example_zh||w.exampleZh,feynman:w.feynman||'在真实场景中反复使用这个词。',nativeTip:w.native_tip||'适合旅行和日常交流。',collocations:[`use ${w.word}`],keywords:[w.word]})):null;replaceVocabulary(normalized||localWords());renderCategoryTabs();render();const remoteBook=await api(`/users/${userId}/wordbook`);if(remoteBook){state.wordbook=remoteBook.map(x=>x.id);save();}count();loginReminder();})();
})();
