/* 增量产品层：不改动原页面业务，提供真实词库同步、生词本页面与登录提醒 */
(function () {
  const API='https://english-learning-app-c53p.onrender.com/api', KEY='LUMINA_ENGLISH_EXT_V2';
  const userId=localStorage.getItem('LUMINA_USER_ID')||'local-user';
  const modules={airport:'机场',direction:'问路',taxi:'打车',dining:'点餐',attraction:'景点',chat:'攀谈聊天',hotel:'酒店入住',shopping:'购物',emergency:'紧急情况',work:'工作交流',health:'健康就医',social:'日常社交'};
  const words={airport:'airport airline arrival departure terminal passport visa luggage baggage boarding gate flight delay transfer security customs aisle window seat reservation counter immigration lounge runway ticket agent suitcase'.split(' '),direction:'street avenue road corner block crossing bridge tunnel station subway platform entrance exit north south east west straight nearby opposite beside between behind ahead map landmark traffic-light roundabout intersection address route distance turn walk'.split(' '),taxi:'taxi cab driver fare meter destination pickup drop-off address traffic route highway downtown passenger ride cash change receipt tip card app stop park trunk seatbelt'.split(' '),dining:'menu table reservation waiter order dish appetizer entree dessert beverage water coffee tea bill check service tip spicy sweet salty vegetarian vegan allergy ingredient portion delicious recommend fresh takeaway fork spoon knife napkin'.split(' '),attraction:'museum gallery theater park temple castle palace tower square beach garden monument market ticket guide tour history entrance opening photo view map famous crowded quiet beautiful exhibit culture architecture souvenir'.split(' '),chat:'hello hi welcome goodbye name country hometown travel work family hobby weather music movie weekend friend interesting really perhaps sure agree understand repeat explain thanks sorry excuse please conversation language practice learn fluent question answer opinion plan experience'.split(' '),hotel:'hotel lobby reception reservation room key guest passport single double bed bathroom towel breakfast checkout luggage available quiet noisy elevator wifi password deposit housekeeping'.split(' '),shopping:'shop store mall price cost cheap expensive size color try fitting-room cash card discount sale receipt refund exchange brand gift market customer available small medium large pair'.split(' '),emergency:'help police ambulance hospital danger emergency lost hurt fire accident safe problem phone address medicine urgent doctor call wait theft report'.split(' '),work:'meeting project schedule deadline email message colleague manager office report task plan discuss confirm update question answer available morning afternoon tomorrow'.split(' '),health:'doctor clinic hospital appointment symptom pain fever cough medicine pharmacy prescription allergy emergency healthy rest better worse stomach head tooth'.split(' '),social:'family friend neighbor party dinner invite birthday weekend together visit call message free busy favorite congratulations welcome introduce enjoy'.split(' ')};
  let state=JSON.parse(localStorage.getItem(KEY)||'{}'); state.wordbook=Array.isArray(state.wordbook)?state.wordbook:[]; state.lastLogin=state.lastLogin||''; state.apiBase=API;
  const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
  const api=async(path,opt={})=>{try{const r=await fetch(state.apiBase+path,{headers:{'Content-Type':'application/json'},...opt});return r.ok?(r.status===204?true:r.json()):null;}catch(e){return null;}};
  const content={
    airport:[['I checked the airport screen for our departure gate.','我查看了机场屏幕上的出发登机口。','把 airport 想成机场入口的大牌子：所有航班都从这里开始找。'],['The airline sent me a message about a two-hour delay.','航空公司发消息告诉我航班延误两小时。','airline 是“空中的 airline”：负责把乘客和飞机连起来的航空公司。'],['Our arrival at Heathrow is scheduled for 6:30 p.m.','我们预计晚上六点半抵达希思罗机场。','arrival 就是“到达”：火车到站、飞机落地都可以用它。'],['The departure board shows that our flight is on time.','出发信息牌显示我们的航班准点。','departure 是“离开”：departure board 就是告诉你谁要离开的牌子。'],['Please go to Terminal 2 for international flights.','国际航班请前往二号航站楼。','terminal 是“终点站/航站楼”，机场里不同航班从不同 terminal 出发。']],
    direction:[['The museum is two blocks north of the station.','博物馆在车站以北两个街区。','block 不是电脑积木，而是城市道路之间的一整块街区。'],['Turn left at the second traffic light.','在第二个红绿灯处左转。','turn left 就像把方向盘向左转，表示“左转”。'],['Walk straight until you see the blue bridge.','一直直走，直到看到那座蓝色的桥。','straight 是“直的”，问路时 walk straight 就是不要拐弯。'],['The pharmacy is opposite the bank.','药店在银行的对面。','opposite 可以想成两个人面对面站着，表示“在……对面”。'],['The subway entrance is beside the bookstore.','地铁入口在书店旁边。','beside 就是“在旁边”，比 near 更强调紧挨着。']],
    taxi:[['Could you take me to the central station?','请送我到中央车站。','destination 是旅程要到达的终点，打车时就是你告诉司机的地方。'],['The driver turned on the meter before we left.','司机出发前打开了计价器。','meter 像出租车里的小秤，车走多远它就计算多少钱。'],['There was heavy traffic downtown.','市中心交通很拥堵。','traffic 不是“交通工具”，而是路上车流的总称。'],['Please drop me off in front of the hotel.','请在酒店门口让我下车。','drop off 就像把人轻轻放下，表示“送到某处下车”。'],['May I have a receipt, please?','可以给我一张收据吗？','receipt 是付款后的纸条，注意 p 不发音。']],
    dining:[['Could we have a table for two, please?','请给我们一张两人桌。','table 在餐厅里通常不是普通桌子，而是“餐桌/座位”。'],['I would like the grilled fish as my main course.','我想要烤鱼作为主菜。','main course 是一顿饭的主菜，就像菜单的主角。'],['Could you make this dish less spicy?','这道菜可以少放点辣吗？','spicy 来自 spice（香料），看到它就想到舌头被香料刺激的感觉。'],['Do you have any vegetarian options?','你们有素食选项吗？','vegetarian 指不吃肉的人或食物，点餐时非常实用。'],['Could we get the bill when you have a moment?','方便的时候可以把账单给我们吗？','bill 是账单，不是“钞票”；餐后 ask for the bill。']],
    attraction:[['The museum has an excellent collection of local art.','这座博物馆收藏了很棒的当地艺术品。','museum 是保存和展示历史、艺术物品的地方。'],['The castle offers a beautiful view of the valley.','这座城堡可以俯瞰美丽的山谷。','view 是眼睛看到的景色，也可以理解为“视野”。'],['The guided tour starts at ten o’clock.','导览团十点开始。','guide 既可以是“导游”，也可以是“带路/指导”。'],['The square is crowded during the festival.','节日期间广场很拥挤。','square 是四四方方的城市公共空间，中文常译为“广场”。'],['Photography is not allowed inside the gallery.','画廊内禁止拍照。','gallery 是展示艺术作品的长廊或画廊。']],
    chat:[['Nice to meet you. Where are you from?','很高兴认识你。你来自哪里？','from 后面接地点，聊天时用来询问对方来自哪里。'],['What do you usually do on weekends?','你周末通常做什么？','usually 表示“通常”，是开启轻松聊天的高频词。'],['That sounds interesting. Tell me more.','听起来很有意思，再多说一点。','interesting 不只是“有趣”，也是表示你愿意继续听的礼貌回应。'],['I am learning English for travel.','我为了旅行正在学英语。','learn 是“学习”，for travel 说明学习的目的。'],['Could you say that again, please?','你可以再说一遍吗？','again 就是“再一次”，听不清时直接礼貌地请求重复。']]
  };
  const localWords=()=>Object.entries(words).flatMap(([cat,list])=>list.map((word,i)=>{const pack=content[cat]||[['I use this word in a real conversation.','我在真实对话中使用这个词。',`把 ${word} 放进你自己的短句里。`]];const item=pack[i%pack.length];return {id:`local_${cat}_${i}`,word,category:cat,meaning:`${modules[cat]}场景：${word}`,phonetic:'',level:'A1 FOUNDATION',pos:'高频表达',collocations:[`${word} in context`],exampleEn:item[0].replace(/\b(airport|airline|arrival|departure|terminal|passport|visa|luggage|boarding|customs|security|gate|flight|delay|transfer|aisle|window|seat|reservation|counter|immigration|street|avenue|road|corner|block|crossing|bridge|tunnel|station|subway|platform|entrance|exit|north|south|east|west|straight|nearby|opposite|beside|taxi|cab|driver|fare|meter|destination|pickup|drop-off|address|traffic|route|highway|downtown|passenger|ride|cash|change|receipt|tip|menu|table|reservation|waiter|order|dish|appetizer|entree|dessert|beverage|water|coffee|bill|service|spicy|vegetarian|allergy|ingredient|portion|delicious|recommend|museum|gallery|theater|park|temple|castle|palace|tower|square|beach|garden|monument|market|ticket|guide|tour|history|exhibit|souvenir|hello|welcome|goodbye|name|country|hometown|travel|work|family|hobby|weather|music|movie|weekend|friend|interesting|agree|understand|thanks|conversation|hotel|lobby|reception|room|key|shopping|price|doctor|meeting|family)\b/i,word),exampleZh:item[1],feynman:item[2],nativeTip:'用完整短句记忆，而不是孤立背诵。',keywords:[word]};}));
  const replaceVocabulary=rows=>{const list=rows;VOCABULARY_DATABASE.splice(0,VOCABULARY_DATABASE.length,...list);CATEGORIES.splice(0,CATEGORIES.length,{id:'all',name:'全部词汇',icon:'✨'},...Object.entries(modules).map(([id,name])=>({id,name,icon:'•'})));};
  const style=document.createElement('style');style.textContent='.ext-panel{margin:24px auto;max-width:1280px;display:flex;gap:12px;flex-wrap:wrap}.ext-card{background:rgba(255,255,255,.72);border:1px solid #ddd1c5;border-radius:16px;padding:18px;flex:1;min-width:280px}.ext-btn{border:0;border-radius:9px;padding:9px 13px;background:#677d6b;color:#fff;cursor:pointer}.ext-nav{margin-left:8px}.ext-modal{position:fixed;inset:0;background:rgba(46,41,38,.55);z-index:99;display:flex;align-items:center;justify-content:center;padding:18px}.ext-dialog{background:#f6f3ed;width:min(680px,100%);max-height:86vh;overflow:auto;border-radius:18px;padding:22px;position:relative}.ext-close{position:absolute;right:16px;top:12px;border:0;background:none;font-size:25px;cursor:pointer}.ext-word{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #e2d8ce;padding:12px 0;gap:10px}.ext-actions{display:flex;gap:7px}.ext-actions button{border:0;border-radius:8px;padding:7px 9px;cursor:pointer}.ext-remember{background:#677d6b;color:white}.ext-unsure{background:#dcc7b5;color:#513f35}.ext-bell{position:fixed;inset:0;background:rgba(46,41,38,.6);z-index:100;display:flex;align-items:center;justify-content:center}.ext-bell-box{background:#f6f3ed;border-radius:18px;padding:30px;max-width:390px;text-align:center}.ext-bell-x{float:right;border:0;background:none;font-size:26px;cursor:pointer}';document.head.append(style);
  const panel=document.createElement('section');panel.className='ext-panel';panel.innerHTML='<div class="ext-card"><h3>📒 生词本</h3><p id="extCount">正在同步…</p><button class="ext-btn" id="extOpenBook">打开生词本</button><button class="ext-btn ext-nav" id="extAdd">＋ 添加当前词</button></div><div class="ext-card"><h3>🔔 每日上线提醒</h3><p id="extReminder">每天重新打开网页时检查未复习生词。</p><button class="ext-btn" id="extEnable">开启提醒</button><small id="extStatus" style="display:block;margin-top:9px"></small></div>';document.querySelector('.app-shell').append(panel);
  const find=id=>VOCABULARY_DATABASE.find(w=>w.id===id);
  const count=()=>{document.querySelector('#extCount').textContent=`已记录 ${state.wordbook.length} 个生词`;document.querySelector('#extReminder').textContent=state.wordbook.length?`还有 ${state.wordbook.length} 个生词需要复习`:'暂无待复习生词';};
  function book(){const modal=document.createElement('div');modal.className='ext-modal';modal.innerHTML='<div class="ext-dialog"><button class="ext-close">×</button><h2>📒 我的生词本</h2><p>“记住了”会移除；“比较模糊”会继续保留。</p><div id="extRows"></div></div>';document.body.append(modal);const rows=modal.querySelector('#extRows'),list=state.wordbook.map(find).filter(Boolean);rows.innerHTML=list.length?list.map(w=>`<div class="ext-word"><span><strong>${w.word}</strong><br><small>${w.meaning}</small></span><span class="ext-actions"><button class="ext-remember" data-a="r" data-id="${w.id}">记住了</button><button class="ext-unsure" data-a="u" data-id="${w.id}">比较模糊</button></span></div>`).join(''):'<p>生词本还是空的，先去词卡添加几个吧。</p>';modal.querySelector('.ext-close').onclick=()=>modal.remove();rows.querySelectorAll('button').forEach(btn=>btn.onclick=async()=>{const id=btn.dataset.id;if(btn.dataset.a==='r'){state.wordbook=state.wordbook.filter(x=>x!==id);save();await api(`/users/${userId}/wordbook/${id}`,{method:'DELETE'});modal.remove();count();book();}else{await api(`/users/${userId}/wordbook/${id}`,{method:'PUT',body:'{}'});btn.textContent='已保留';btn.disabled=true;}});}
  panel.querySelector('#extOpenBook').onclick=book;
  panel.querySelector('#extAdd').onclick=async()=>{const w=currentFilteredList[currentWordIndex];if(!state.wordbook.includes(w.id)){state.wordbook.unshift(w.id);save();await api(`/users/${userId}/wordbook`,{method:'POST',body:JSON.stringify({wordId:w.id})});count();}};
  function loginReminder(){if(!state.wordbook.length||state.lastLogin===new Date().toISOString().slice(0,10))return;const box=document.createElement('div');box.className='ext-bell';box.innerHTML=`<div class="ext-bell-box"><button class="ext-bell-x">×</button><div style="font-size:42px">🔔</div><h2>欢迎回来</h2><p>你的生词本还有 <strong>${state.wordbook.length}</strong> 个词没有复习。</p><button class="ext-btn" id="extGoBook">去看看生词本</button></div>`;document.body.append(box);const close=()=>{state.lastLogin=new Date().toISOString().slice(0,10);save();box.remove();};box.querySelector('.ext-bell-x').onclick=close;box.querySelector('#extGoBook').onclick=()=>{close();book();};}
  panel.querySelector('#extEnable').onclick=async()=>{if('Notification'in window)await Notification.requestPermission();panel.querySelector('#extStatus').textContent='已开启：重新登录网页时显示提醒弹窗';};
  async function loadDetail() { const item=currentFilteredList[currentWordIndex]; if (!item || item.detailLoaded) return; const detail=await api(`/vocabulary/${item.id}`); if (!detail || !detail.meaning) return; Object.assign(item,{meaning:detail.meaning,phonetic:detail.phonetic||'',pos:detail.pos||'常用词',exampleEn:detail.example_en,exampleZh:detail.example_zh,feynman:detail.feynman,nativeTip:detail.native_tip,detailLoaded:true}); render(); }
  (async()=>{const remote=await api('/vocabulary?category=all');if(!remote||remote.length!==3000){document.querySelector('#extStatus').textContent='词库服务正在初始化，请稍后刷新。';return;}replaceVocabulary(remote.map(w=>({...w,phonetic:'',pos:'常用词',level:'A1–B2',meaning:'正在加载词典释义…',exampleEn:'正在加载对应例句…',exampleZh:'',feynman:'正在加载对应记忆提示…',nativeTip:'',collocations:[],keywords:[w.word]})));renderCategoryTabs();render();new MutationObserver(loadDetail).observe(UI.cardWord,{childList:true,subtree:true,characterData:true});loadDetail();const remoteBook=await api(`/users/${userId}/wordbook`);if(remoteBook){state.wordbook=remoteBook.map(x=>x.id);save();}count();loginReminder();})();
})();
