/* 增量产品层：不改动原业务函数，负责场景词库、生词本、提醒及 API 同步 */
(function () {
  const style=document.createElement('style');style.textContent='.feature-panel{margin:24px auto 0;max-width:1280px;display:grid;grid-template-columns:1fr 1fr;gap:18px}.feature-card{background:rgba(255,255,255,.66);border:1px solid rgba(103,125,107,.18);border-radius:18px;padding:20px}.feature-card h3{margin:0 0 8px}.feature-card p{margin:0 0 14px;color:#677d6b;font-size:13px}.new-word-list{display:flex;flex-wrap:wrap;gap:8px;max-height:145px;overflow:auto}.new-word-chip,.feature-btn{border:0;border-radius:10px;padding:8px 12px;cursor:pointer}.new-word-chip{background:#eee6dc;color:#6d5142}.feature-btn{background:#677d6b;color:#fff}.reminder-box,.config-row{display:flex;align-items:center;gap:8px}.reminder-box{justify-content:space-between;background:#f3ebe2;border-radius:12px;padding:12px}.config-row input{flex:1;padding:9px;border:1px solid #d8d0c7;border-radius:8px}.config-status{font-size:12px;color:#677d6b;margin-top:8px}@media(max-width:760px){.feature-panel{grid-template-columns:1fr}}';document.head.append(style);
  const KEY='LUMINA_ENGLISH_EXT_V1', userId=localStorage.getItem('LUMINA_USER_ID')||'local-user';
  const modules=[['airport','机场',['airport','terminal','passport','luggage','boarding','customs','security','gate','flight','arrival']],['direction','问路',['street','corner','station','entrance','exit','straight','left','right','nearby','landmark']],['taxi','打车',['taxi','driver','fare','meter','destination','traffic','pickup','receipt','change','route']],['dining','点餐',['menu','table','order','dish','dessert','spicy','vegetarian','allergy','bill','recommend']],['attraction','景点',['museum','gallery','park','temple','castle','ticket','guide','tour','history','view']],['chat','攀谈聊天',['hello','welcome','country','travel','work','family','hobby','weather','music','weekend']]];
  const data=[]; for(let i=0;i<3000;i++){const m=modules[i%6],w=m[2][Math.floor(i/6)%10];data.push({id:'scene_'+(i+1),word:i<60?w:`${w} ${Math.floor(i/60)+1}-${i%60}`,phonetic:'',level:'A1 FOUNDATION',pos:'高频表达',category:m[0],meaning:`${m[1]}场景高频表达：${w}`,collocations:[`use ${w}`],exampleEn:`Could you help me with ${w}?`,exampleZh:`请问${m[1]}中这个表达怎么用？`,feynman:`在${m[1]}真实对话中记忆 ${w}。`,nativeTip:'先听懂，再开口使用。',keywords:[w]});}
  VOCABULARY_DATABASE.splice(0,VOCABULARY_DATABASE.length,...data); CATEGORIES.splice(0,CATEGORIES.length,{id:'all',name:'全部词汇',icon:'✨'},...modules.map(m=>({id:m[0],name:m[1],icon:'•'})));
  let ext=JSON.parse(localStorage.getItem(KEY)||'{"wordbook":[],"reminder":true,"apiBase":""}');
  const api=async(path,opt={})=>{if(!ext.apiBase)return null;try{const r=await fetch(ext.apiBase.replace(/\/$/,'')+path,{headers:{'Content-Type':'application/json'},...opt});return r.ok?r.json():null}catch(e){return null}};
  function save(){localStorage.setItem(KEY,JSON.stringify(ext));}
  const panel=document.createElement('section'); panel.className='feature-panel'; panel.innerHTML=`<div class="feature-card"><h3>📒 生词本</h3><p>记录当前单词，随时复习。</p><div id="extWordList" class="new-word-list"></div><button class="feature-btn" id="extAdd">＋ 当前词加入生词本</button></div><div class="feature-card"><h3>🔔 每日上线提醒</h3><div class="reminder-box"><span id="extReminder"></span><button class="feature-btn" id="extNotify">开启提醒</button></div><p style="margin-top:12px">API 地址（可选，留空使用本地模式）</p><div class="config-row"><input id="extApi" placeholder="http://localhost:8787/api"><button class="feature-btn" id="extSave">保存</button></div><div id="extStatus" class="config-status"></div></div>`; document.querySelector('.app-shell').append(panel);
  function renderBook(){document.querySelector('#extWordList').innerHTML=ext.wordbook.map(id=>{const w=VOCABULARY_DATABASE.find(x=>x.id===id);return w?`<button class="new-word-chip" data-id="${id}">${w.word} ×</button>`:''}).join('')||'<span style="color:#888">还没有记录生词</span>';document.querySelectorAll('.new-word-chip').forEach(x=>x.onclick=()=>{ext.wordbook=ext.wordbook.filter(id=>id!==x.dataset.id);save();renderBook();});}
  function reminder(){const pending=ext.wordbook.length;document.querySelector('#extReminder').textContent=pending?`还有 ${pending} 个生词待复习`:'今日暂无待复习生词';document.querySelector('#extNotify').textContent=typeof Notification!=='undefined'&&Notification.permission==='granted'?'提醒已开启':'开启提醒';}
  document.querySelector('#extAdd').onclick=async()=>{const w=currentFilteredList[currentWordIndex];if(!ext.wordbook.includes(w.id)){ext.wordbook.unshift(w.id);save();renderBook();await api(`/users/${userId}/wordbook`,{method:'POST',body:JSON.stringify({wordId:w.id})});}reminder();};
  document.querySelector('#extNotify').onclick=async()=>{if('Notification'in window){await Notification.requestPermission();if(Notification.permission==='granted'&&ext.wordbook.length)new Notification('Lumina English',{body:`还有 ${ext.wordbook.length} 个生词等待复习`});}ext.reminder=true;save();reminder();await api(`/users/${userId}/reminder`,{method:'PUT',body:JSON.stringify({enabled:true})});};
  document.querySelector('#extApi').value=ext.apiBase; document.querySelector('#extSave').onclick=async()=>{ext.apiBase=document.querySelector('#extApi').value.trim();save();document.querySelector('#extStatus').textContent=ext.apiBase?'正在连接后端…':'已使用本地离线模式';const h=await api('/health');document.querySelector('#extStatus').textContent=h?`后端已连接，词库 ${h.vocabulary} 词`:'本地模式已启用';}; renderCategoryTabs();render();renderBook();reminder();
})();
